# Generated by Django 4.1.5 on 2023-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('duedate', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('progress', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
