# Generated by Django 4.1.5 on 2023-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_task_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=60),
        ),
    ]
