# Generated by Django 4.1.5 on 2023-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_task_duedate_alter_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=64),
        ),
    ]
