# Generated by Django 4.1.5 on 2023-02-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_alter_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(),
        ),
    ]
