# Generated by Django 4.1.5 on 2023-02-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_task_duedate_alter_task_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
