# Generated by Django 4.1.5 on 2023-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_remove_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
