# Generated by Django 4.1.5 on 2023-02-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_task_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
