# Generated by Django 4.1.5 on 2023-02-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_alter_task_edited_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='edited_on',
            new_name='modified',
        ),
    ]
