# Generated by Django 4.1.5 on 2023-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_alter_task_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
